import type { Metadata } from "next";
import "./globals.css";
import {Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { ClerkProvider} from '@clerk/nextjs'
import ThemeProvider from "@/components/theme-provider";



const inter= Inter({subsets:["latin"]})


;

export const metadata: Metadata = {
  title: "Feedback Fusion App",
  description: "Generated by helo of Dipesh Malvia nextjs tutorial.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

   
    <html
      lang="en" suppressHydrationWarning
      className={cn("h-full", "antialiased", "font-sans")}
    >
      <body className={`${inter} min-h-full flex flex-col`}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
     <Navbar/>
       <main className="flex-1 container mx-auto px-4 py-8">  {children}</main>
        <Footer/>
        <Toaster/>
        </ThemeProvider>
      </body>
    </html>
     </ClerkProvider>
  );
}
